### ISSUE TITLE
application/x-zip-compressed

### ISSUE THREAD

**Issue by yrm006** [oakserver/media_types#10]
The Windows sends content-type: 'application/x-zip-compressed' in multipart/form-data, so I can't receive the ".zip" file.

Consider adding  'application/x-zip-compressed' to "db.ts".

Thank you,

**Comment by kitsonk** [comment]
@yrm006 `db.ts` is adapted directly from https://github.com/jshttp/mime-db which documents how it sources its media types.  I don't want to maintain any bespoke entries.  If it gets added to mime-db, it will get added here.

**Comment by yrm006** [comment]
Thank you reply, I understand.

So is there a way to support 'x-zip-compressed' without adding 'x-zip-compressed' to "db.ts"?

**Comment by kitsonk** [comment]
@yrm006 do you mean with oak?

I looked at the code in oak, it feels like there should just be an option to allow "ignoring" unmatched content-types, so that it doesn't throw, but still makes the file available, just without an extension.

**Comment by yrm006** [comment]
yes I do, i mean in oak.

I saw 'oak/multipart.ts:172', it calls 'getFile(...)'. There seems to be no way to ignore it.
If you know how to ignore it, please let me know.

Thank you,

**Comment by yrm006** [comment]
I temporaly could solved by rewrite the contentType on the client side:
```
    const fdata = new FormData(theForm);
    if(fdata.get("myfile").type === "application/x-zip-compressed"){
        const reader = new FileReader();
        reader.addEventListener('load', (event) => {
            const blob = new Blob([event.target.result], {type : 'application/zip'});
            fdata.delete("myfile");
            fdata.append("myfile", blob, theForm.myfile.files[0].name);
        });
        reader.readAsArrayBuffer(theForm.myfile.files[0]);
    }
```

And also I have posted to the 'mime-db' which you taught.
  https://github.com/jshttp/mime-db/issues/245


Thank you so much for awesome repo 'oak' and 'deno'!
